# FASE 1: CRIAR O BANCO DE DADOS (SCHEMA OU DATABASE):
CREATE SCHEMA EC1_CC1N;

# FASE 2: SELECIONAR O NOVO SCHEMA OU DATABASE PARA USO:
USE EC1_CC1N;

# FASE 3: CRIANDO AS TABELAS SEM CHAVES ESTRANGEIRAS

# CRIANDO A TABELA FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES(
    FORNEC_COD INT PRIMARY KEY,
    FORNEC_NOME VARCHAR(45) NOT NULL,
    FORNEC_RUA VARCHAR(45) NOT NULL,
    FORNEC_NUMRUA INT,
    FORNEC_BAIRRO VARCHAR(45) NOT NULL,
    FORNEC_CIDADE VARCHAR(45) NOT NULL,
    FORNEC_ESTADO VARCHAR(45) NOT NULL,
    FORNEC_PAIS VARCHAR(30) NOT NULL,
    FORNEC_CODPOSTAL VARCHAR(10) NOT NULL,
    FORNEC_TELEFONE VARCHAR(15) NOT NULL,
    FORNEC_CONTATO TEXT NOT NULL
);

# CRIANDO A TABELA FILIAIS
CREATE TABLE IF NOT EXISTS FILIAIS(
    FILIAL_COD INT PRIMARY KEY,
    FILIAL_NOME VARCHAR(45) NOT NULL,
    FILIAL_RUA VARCHAR(100) NOT NULL,
    FILIAL_NUMRUA INT,
    FILIAL_BAIRRO VARCHAR(50) NOT NULL,
    FILIAL_CIDADE VARCHAR(50) NOT NULL,
    FILIAL_ESTADO VARCHAR(50) NOT NULL,
    FILIAL_PAIS VARCHAR(50) NOT NULL,
    FILIAL_CODPOSTAL VARCHAR(10) NOT NULL,
    FILIAL_CAPACIDADE TEXT NOT NULL
);

# CRIANDO A TABELA PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS(
    PROD_COD INT PRIMARY KEY,
    PROD_NOME VARCHAR(50) NOT NULL,
    PROD_DESCRICAO TEXT NOT NULL,
    PROD_ESPECTEC TEXT NOT NULL,
    PROD_QUANT DECIMAL(10,3) NOT NULL,
    PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
    PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
    PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);

# FASE 4: CRIAR AS TABELAS COM DEPENDÊNCIA DE CHAVE ESTRANGEIRA

# CRIANDO A TABELA PEDIDOS
CREATE TABLE IF NOT EXISTS PEDIDOS(
    PED_CODIGO INT PRIMARY KEY,
    PED_DATA DATE NOT NULL,
    PED_HORA TIME NOT NULL,
    PED_PREVISAO DATE NOT NULL,
    PED_STATUS ENUM('PENDENTE','CONCLUÍDO','EM ESPERA'),
    PED_FORNECEDOR INT NOT NULL,
    CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR)
    REFERENCES FORNECEDORES(FORNEC_COD)
);

# CRIANDO A TABELA RECEBIMENTOS
CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
    RECEB_DATA DATE NOT NULL,
    RECEB_HORA TIME NOT NULL,
    RECEB_QUANT_PROD DECIMAL(10,3),
    RECEB_CONDICAO TEXT NOT NULL,
    RECEB_PEDIDOS INT PRIMARY KEY,
    CONSTRAINT FK_PEDIDOS FOREIGN KEY(RECEB_PEDIDOS)
    REFERENCES PEDIDOS(PED_CODIGO)
);

# CRIANDO A TABELA PEDIDOS_PRODUTOS
CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
    PDPR_PEDIDOS INT,
    PDPR_PRODUTOS INT,
    PRIMARY KEY(PDPR_PEDIDOS,PDPR_PRODUTOS),
    PDPR_QUANT DECIMAL(10,3) NOT NULL,
    CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY(PDPR_PEDIDOS)
    REFERENCES PEDIDOS(PED_CODIGO),
    CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY(PDPR_PRODUTOS)
    REFERENCES PRODUTOS(PROD_COD)
);

# CRIANDO A TABELA FILIAIS_PRODUTOS
CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
    FLPR_FILIAL INT,
    FLPR_PRODUTOS INT,
    PRIMARY KEY(FLPR_FILIAL,FLPR_PRODUTOS),
    FLPR_QUANT DECIMAL(10,3) NOT NULL,
    CONSTRAINT FLPR_FK_FILIAIS FOREIGN KEY(FLPR_FILIAL)
    REFERENCES FILIAIS(FILIAL_COD),
    CONSTRAINT FLPR_FK_PRODUTOS FOREIGN KEY(FLPR_PRODUTOS)
    REFERENCES PRODUTOS(PROD_COD)
);

# CRIANDO A TABELA FORNECEDORES_PRODUTOS
CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
    FRPR_FORNECEDOR INT,
    FRPR_PRODUTOS INT,
    PRIMARY KEY(FRPR_FORNECEDOR,FRPR_PRODUTOS),
    CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDOR)
    REFERENCES FORNECEDORES(FORNEC_COD),
    CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS)
    REFERENCES PRODUTOS(PROD_COD)
);

# FASE 5: EXEMPLOS DE ALTER PARA CADA TABELA

# Alterar a tabela FORNECEDORES: Adicionar uma nova coluna para e-mail
ALTER TABLE FORNECEDORES ADD FORNEC_EMAIL VARCHAR(100);

# Alterar a tabela FILIAIS: Modificar o tipo da coluna FILIAL_CAPACIDADE
ALTER TABLE FILIAIS MODIFY FILIAL_CAPACIDADE INT;

# Alterar a tabela PRODUTOS: Renomear a coluna PROD_DESCRICAO para PROD_DESC
ALTER TABLE PRODUTOS CHANGE PROD_DESCRICAO PROD_DESC TEXT;

# Alterar a tabela PEDIDOS: Adicionar um índice na coluna PED_DATA
CREATE INDEX idx_ped_data ON PEDIDOS(PED_DATA);

# Alterar a tabela RECEBIMENTOS: Remover a coluna RECEB_CONDICAO
ALTER TABLE RECEBIMENTOS DROP COLUMN RECEB_CONDICAO;

# Alterar a tabela PEDIDOS_PRODUTOS: Modificar a coluna PDPR_QUANT para aceitar valores nulos
ALTER TABLE PEDIDOS_PRODUTOS MODIFY PDPR_QUANT DECIMAL(10,3) NULL;

# Alterar a tabela FILIAIS_PRODUTOS: Adicionar um comentário à tabela
ALTER TABLE FILIAIS_PRODUTOS COMMENT = 'Tabela associativa entre filiais e produtos';

# Alterar a tabela FORNECEDORES_PRODUTOS: Adicionar um índice na coluna FRPR_FORNECEDOR
CREATE INDEX idx_frpr_fornecedor ON FORNECEDORES_PRODUTOS(FRPR_FORNECEDOR);

# FASE 6: COMANDO DROP PARA O SCHEMA
DROP SCHEMA EC1_CC1N;