-- Criando o banco de dados AEROPORTO_DB
CREATE DATABASE IF NOT EXISTS AEROPORTO_DB;

-- Usando o banco de dados criado
USE AEROPORTO_DB;

-- Criando a tabela PASSAGEIROS
CREATE TABLE IF NOT EXISTS PASSAGEIROS (
    PASS_ID INT AUTO_INCREMENT PRIMARY KEY,
    PASS_NOME VARCHAR(100) NOT NULL,
    PASS_EMAIL VARCHAR(100),
    PASS_TELEFONE VARCHAR(20)
);

-- Criando a tabela RESERVAS
CREATE TABLE IF NOT EXISTS RESERVAS (
    RES_ID INT AUTO_INCREMENT PRIMARY KEY,
    PASS_ID INT,
    DATA_RESERVA DATE,
    FOREIGN KEY (PASS_ID) REFERENCES PASSAGEIROS(PASS_ID)
);

-- Criando a tabela VOOS
CREATE TABLE IF NOT EXISTS VOOS (
    VOO_ID INT AUTO_INCREMENT PRIMARY KEY,
    VOO_DESTINO VARCHAR(100),
    VOO_PARTIDA VARCHAR(100),
    VOO_DATA DATE
);

-- Criando a tabela COMPANHIAS
CREATE TABLE IF NOT EXISTS COMPANHIAS (
    COMP_ID INT AUTO_INCREMENT PRIMARY KEY,
    COMP_NOME VARCHAR(100),
    COMP_CNPJ VARCHAR(14)
);

-- Criando a tabela RESERVAS_VOOS
CREATE TABLE IF NOT EXISTS RESERVAS_VOOS (
    RES_ID INT,
    VOO_ID INT,
    PRIMARY KEY (RES_ID, VOO_ID),
    FOREIGN KEY (RES_ID) REFERENCES RESERVAS(RES_ID),
    FOREIGN KEY (VOO_ID) REFERENCES VOOS(VOO_ID)
);

-- Criando a tabela COMPANHIAS_VOOS
CREATE TABLE IF NOT EXISTS COMPANHIAS_VOOS (
    COMP_ID INT,
    VOO_ID INT,
    PRIMARY KEY (COMP_ID, VOO_ID),
    FOREIGN KEY (COMP_ID) REFERENCES COMPANHIAS(COMP_ID),
    FOREIGN KEY (VOO_ID) REFERENCES VOOS(VOO_ID)
);

-- Alterar Tabela PASSAGEIROS: Adicionando coluna PASS_DATA_NASCIMENTO
ALTER TABLE PASSAGEIROS ADD COLUMN IF NOT EXISTS PASS_DATA_NASCIMENTO DATE;

-- Alterar Tabela RESERVAS: Modificando DATA_RESERVA para aceitar valores nulos
ALTER TABLE RESERVAS MODIFY COLUMN DATA_RESERVA DATE NULL;

-- Alterar Tabela VOOS: Renomeando a coluna VOO_DESTINO para DESTINO_FINAL
ALTER TABLE VOOS CHANGE COLUMN VOO_DESTINO DESTINO_FINAL VARCHAR(100);

-- Alterar Tabela COMPANHIAS: Adicionando índice na coluna COMP_NOME
ALTER TABLE COMPANHIAS ADD INDEX IF NOT EXISTS idx_nome (COMP_NOME);

-- Alterar Tabela RESERVAS_VOOS: Adicionando coluna STATUS_CONFIRMACAO
ALTER TABLE RESERVAS_VOOS ADD COLUMN IF NOT EXISTS STATUS_CONFIRMACAO VARCHAR(20) DEFAULT 'PENDENTE';

-- Alterar Tabela COMPANHIAS_VOOS: Modificando a coluna COMP_CNPJ para não aceitar valores nulos
ALTER TABLE COMPANHIAS_VOOS MODIFY COLUMN COMP_CNPJ VARCHAR(14) NOT NULL;


-- Remover a tabela RESERVAS_VOOS
DROP TABLE IF EXISTS RESERVAS_VOOS;

-- Remover a tabela COMPANHIAS_VOOS
DROP TABLE IF EXISTS COMPANHIAS_VOOS;

-- Remover a tabela VOOS
DROP TABLE IF EXISTS VOOS;

-- Remover a tabela COMPANHIAS
DROP TABLE IF EXISTS COMPANHIAS;

-- Remover a tabela RESERVAS
DROP TABLE IF EXISTS RESERVAS;

-- Remover a tabela PASSAGEIROS
DROP TABLE IF EXISTS PASSAGEIROS;

-- Remover o banco de dados AEROPORTO_DB
DROP DATABASE IF EXISTS AEROPORTO_DB;
