-- Criar o banco de dados LOJA_INOVA_TECH
CREATE DATABASE IF NOT EXISTS LOJA_INOVA_TECH;

-- Selecionar o banco de dados
USE LOJA_INOVA_TECH;

-- Tabela CLIENTES
CREATE TABLE CLIENTES (
    CLIENTE_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    TELEFONE VARCHAR(15),
    ENDERECO VARCHAR(255)
);

-- Tabela FORNECEDORES
CREATE TABLE FORNECEDORES (
    FORNECEDOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(15),
    EMAIL VARCHAR(100)
);

-- Tabela PRODUTOS
CREATE TABLE PRODUTOS (
    PRODUTO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL,
    ESTOQUE INT NOT NULL,
    FORNECEDOR_ID INT,
    FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDORES(FORNECEDOR_ID)
);

-- Tabela VENDAS
CREATE TABLE VENDAS (
    VENDA_ID INT PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INT,
    DATA_VENDA DATE NOT NULL,
    TOTAL DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
);

-- Tabela ITENS_VENDA (para armazenar os produtos vendidos em cada venda)
CREATE TABLE ITENS_VENDA (
    ITEM_ID INT PRIMARY KEY AUTO_INCREMENT,
    VENDA_ID INT,
    PRODUTO_ID INT,
    QUANTIDADE INT NOT NULL,
    PRECO_UNITARIO DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(VENDA_ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(PRODUTO_ID)
);

-- Etapa 1: Criar o banco de dados LOJA_INOVA_TECH
CREATE DATABASE IF NOT EXISTS LOJA_INOVA_TECH;

-- Etapa 2: Selecionar o banco de dados
USE LOJA_INOVA_TECH;

-- Etapa 3: Criar as tabelas necessárias

-- Tabela CLIENTES
CREATE TABLE CLIENTES (
    CLIENTE_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    TELEFONE VARCHAR(15),
    ENDERECO VARCHAR(255)
);

-- Tabela FORNECEDORES
CREATE TABLE FORNECEDORES (
    FORNECEDOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(15),
    EMAIL VARCHAR(100)
);

-- Tabela PRODUTOS
CREATE TABLE PRODUTOS (
    PRODUTO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL,
    ESTOQUE INT NOT NULL,
    FORNECEDOR_ID INT,
    FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDORES(FORNECEDOR_ID)
);

-- Tabela VENDAS
CREATE TABLE VENDAS (
    VENDA_ID INT PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INT,
    DATA_VENDA DATE NOT NULL,
    TOTAL DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
);

-- Tabela ITENS_VENDA
CREATE TABLE ITENS_VENDA (
    ITEM_ID INT PRIMARY KEY AUTO_INCREMENT,
    VENDA_ID INT,
    PRODUTO_ID INT,
    QUANTIDADE INT NOT NULL,
    PRECO_UNITARIO DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(VENDA_ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(PRODUTO_ID)
);
