-- ETAPA 1: CRIAR O BANCO DE DADOS COMPANHIA_AEREA
CREATE DATABASE IF NOT EXISTS COMPANHIA_AEREA;

-- ETAPA 2: SELECIONAR O NOVO BANCO DE DADOS
USE COMPANHIA_AEREA;

-- ETAPA 3: CRIAR AS TABELAS RELACIONADAS À COMPANHIA AÉREA

-- Tabela AERONAVES
CREATE TABLE IF NOT EXISTS AERONAVES (
    AERONAVE_ID INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(50) NOT NULL,
    CAPACIDADE INT NOT NULL
);

-- Tabela VOOS
CREATE TABLE IF NOT EXISTS VOOS (
    VOO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO_VOO VARCHAR(10) NOT NULL,
    DESTINO VARCHAR(50) NOT NULL,
    ORIGEM VARCHAR(50) NOT NULL,
    AERONAVE_ID INT,
    FOREIGN KEY (AERONAVE_ID) REFERENCES AERONAVES(AERONAVE_ID)
);

-- Tabela PASSAGEIROS
CREATE TABLE IF NOT EXISTS PASSAGEIROS (
    PASSAGEIRO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL
);

-- Tabela RESERVAS
CREATE TABLE IF NOT EXISTS RESERVAS (
    RESERVA_ID INT PRIMARY KEY AUTO_INCREMENT,
    PASSAGEIRO_ID INT,
    VOO_ID INT,
    DATA_RESERVA DATE NOT NULL,
    FOREIGN KEY (PASSAGEIRO_ID) REFERENCES PASSAGEIROS(PASSAGEIRO_ID),
    FOREIGN KEY (VOO_ID) REFERENCES VOOS(VOO_ID)
);

-- ETAPA 4: SELECIONAR O NOVO BANCO DE DADOS
USE COMPANHIA_AEREA;

-- ETAPA 5: CRIAR AS TABELAS RELACIONADAS À COMPANHIA AÉREA

-- Tabela AERONAVES
CREATE TABLE IF NOT EXISTS AERONAVES (
    AERONAVE_ID INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(50) NOT NULL,
    CAPACIDADE INT NOT NULL
);

-- Índice para busca rápida por MODELO em AERONAVES
CREATE INDEX idx_modelo ON AERONAVES (MODELO);

-- Tabela VOOS
CREATE TABLE IF NOT EXISTS VOOS (
    VOO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO_VOO VARCHAR(10) NOT NULL,
    DESTINO VARCHAR(50) NOT NULL,
    ORIGEM VARCHAR(50) NOT NULL,
    AERONAVE_ID INT,
    FOREIGN KEY (AERONAVE_ID) REFERENCES AERONAVES(AERONAVE_ID)
);

-- Índice para busca rápida por NUMERO_VOO em VOOS
CREATE INDEX idx_numero_voo ON VOOS (NUMERO_VOO);

-- Tabela PASSAGEIROS
CREATE TABLE IF NOT EXISTS PASSAGEIROS (
    PASSAGEIRO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL
);

-- Índice para busca rápida por CPF em PASSAGEIROS
CREATE INDEX idx_cpf ON PASSAGEIROS (CPF);

-- Tabela RESERVAS
CREATE TABLE IF NOT EXISTS RESERVAS (
    RESERVA_ID INT PRIMARY KEY AUTO_INCREMENT,
    PASSAGEIRO_ID INT,
    VOO_ID INT,
    DATA_RESERVA DATE NOT NULL,
    FOREIGN KEY (PASSAGEIRO_ID) REFERENCES PASSAGEIROS(PASSAGEIRO_ID),
    FOREIGN KEY (VOO_ID) REFERENCES VOOS(VOO_ID)
);

-- Visão para listar as reservas de cada passageiro com dados do voo
CREATE VIEW vista_reservas AS
SELECT 
    PASSAGEIROS.NOME AS Passageiro,
    VOOS.NUMERO_VOO AS NumeroVoo,
    VOOS.DESTINO AS Destino,
    VOOS.ORIGEM AS Origem,
    RESERVAS.DATA_RESERVA AS DataReserva
FROM RESERVAS
JOIN PASSAGEIROS ON RESERVAS.PASSAGEIRO_ID = PASSAGEIROS.PASSAGEIRO_ID
JOIN VOOS ON RESERVAS.VOO_ID = VOOS.VOO_ID;

-- ALTER para modificar tabelas
-- Adicionar coluna em AERONAVES
ALTER TABLE AERONAVES ADD ANO_FABRICACAO YEAR;

-- Remover coluna em VOOS
ALTER TABLE VOOS DROP COLUMN ORIGEM;

-- Modificar tipo de coluna em PASSAGEIROS
ALTER TABLE PASSAGEIROS MODIFY COLUMN CPF VARCHAR(11);

-- Renomear coluna em RESERVAS
ALTER TABLE RESERVAS CHANGE COLUMN DATA_RESERVA DATA_VIAGEM DATE;

-- RENAME para renomear uma tabela
RENAME TABLE PASSAGEIROS TO CLIENTES;

-- TRUNCATE para limpar dados das tabelas
TRUNCATE TABLE AERONAVES;
TRUNCATE TABLE VOOS;
TRUNCATE TABLE CLIENTES;
TRUNCATE TABLE RESERVAS;

-- DROP para remover objetos do banco de dados
-- Remover o banco de dados
DROP DATABASE IF EXISTS COMPANHIA_AEREA;

-- Remover tabelas
DROP TABLE IF EXISTS AERONAVES;
DROP TABLE IF EXISTS VOOS;
DROP TABLE IF EXISTS CLIENTES;
DROP TABLE IF EXISTS RESERVAS;

-- Remover índices
DROP INDEX idx_modelo ON AERONAVES;
DROP INDEX idx_numero_voo ON VOOS;
DROP INDEX idx_cpf ON CLIENTES;

-- Remover visões
DROP VIEW IF EXISTS vista_reservas;
